GET http://localhost:5000/api/users

###

POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
  "name": "Jake",
  "email": "test@testing.com",
  "password": "testers",
  "places": "p2"
}
###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "test@testt.com",
  "password": "testing"
}

